# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10

  - name: Papers
    url: /publications/
    weight: 20

  - name: Research & Competitions
    url: /research-competitions/
    weight: 30

  - name: Certificates
    url: /#certificates
    weight: 40

  - name: Awards
    url: /#awards
    weight: 50

  - name: Workshops & Other Activities
    url: /#workshops-activities
    weight: 60
